### PR TITLE
add more elixir/otp versions to run builds against

### PR DESCRIPTION
**Pull request by ayrat555**

### CODE REVIEW

**Comment by phcurado** [comment]
Added an issue for fixing tests on OTP 26 or beyond so it can be tackled before merging this PR.

**Comment by brewerx** [comment]
Hey @phcurado ! I created this PR https://github.com/phcurado/daisy_ui_components/pull/29 as a potential fix for the failing test. If you like the approach I can help migrate other tests.

**Comment by phcurado** [comment]
thank you @brewerx, I didn't know about the assert_html library before, the improvement is great!

**Comment by brewerx** [comment]
Hey @phcurado @ayrat555 . I used this PR content to create https://github.com/phcurado/daisy_ui_components/pull/30 to be able test and do any further changes to make it work with the latest changes in `main`. Hope this helps 👍

**Pull request closed without merging**
